config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  root to:'statics#home'
  resources :ideas, only: [:create]

  get 'ideas/ver/:id', to: 'ideas#show', as: 'ver_idea'
  get 'ideas/:slug/mas/:page', to: 'ideas#index', as: 'idea'
  get 'ideas/:slug/votadas/:page', to:'ideas#mas_votadas', as: 'mas_votadas'
  get 'ideas/:slug/proponer', to: 'ideas#new', as: 'new_idea'
  get 'ideas/:slug/la_verdad', to: 'ideas#la_verdad', as: 'la_verdad'

  post 'votes/:id', to:'votes#create', as: 'vote'
  delete 'votes/:id', to:'votes#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :theme

  validates :content,length: { minimum: 6, maximum:1000 }
  validates :content, presence: true, uniqueness: true
end

app/models/theme.rb
class Theme < ApplicationRecord

  has_many :ideas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  before_action :idea_params , :only => [:create]

  before_action :set_theme, :only => [:la_verdad,:new,:index,:mas_votadas]

  def index
    @ideas = @theme.ideas.paginate(:page => params[:page], :per_page => 8)
  end

  def create
    @idea = Idea.new(idea_params)

    if @idea.save
      redirect_to "/ideas/#{@idea.theme.slug}/mas/1"
    else
      flash[:danger] = @idea.errors
      redirect_to new_idea_path(@idea.theme.slug)
    end
  end

  def new
    @idea = Idea.new
  end

  def mas_votadas
    @ideas = @theme.ideas.order(votePlus: :desc).paginate(:page => params[:page], :per_page => 8)
    render 'ideas/index'
  end

  def show
    @idea = Idea.find(params[:id])
  end

  def la_verdad

  end

  private

  def set_theme
    @theme =  Theme.find_by(:slug => params[:slug])
  end

  def idea_params
    params.require(:idea).permit(:content,:theme_id)
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def home
    @tema = Theme.last
    redirect_to "/ideas/#{@tema.slug}/proponer"
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  before_action :set_idea

  def create
    counter = @idea.votePlus
    @idea.update({votePlus: counter +=  1})

  end

  def destroy

    counterLess = @idea.voteLess
    @idea.update({voteLess: counterLess +=  1})
  end

  private

  def set_idea
    @idea = Idea.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def facebook_share_url url, msj
    "https://www.facebook.com/sharer/sharer.php?u=#{url}&title=#{msj}"
  end

  def twitter_share_url url, msj
    "https://www.twitter.com/intent/tweet?url=#{url}&text=#{msj}"
  end

  def social_share url=request.original_url, msj='Mira esto!'
    "<a  href='#{facebook_share_url url, msj}' target='_blank'>  <i class='fa fa-facebook fa-lg'></i> </a>".html_safe +
    "<a target='_blank' href='#{twitter_share_url url, msj}'><i class='fa fa-twitter fa-lg'></i> </a>".html_safe
  end

end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/ideas/_idea.html.erb
<div class="post">
  <section class="col-md-6 post-content">
    <p><%= idea.content %></p>


    <section class="share-container pull-left">
      <%= social_share request.base_url+'/ideas/ver/'+idea.id.to_s,'Para mí, esto es la Libertad de Expresión #ParaTiQueEs' %>
    </section>

    <section class="like-container pull-right">
      <span class="counter" id="counter-plus-<%= idea.id %>"><%= idea.votePlus %></span>

      <%= link_to vote_path(idea.id), method: :post,  remote: true, id:"vote-up-#{idea.id}"  do %>
        <i class="fa fa-lg fa-thumbs-up vote vote-up" aria-hidden="true"></i>
      <% end %>

      <span class="counter" id="counter-less-<%= idea.id %>"><%= idea.voteLess %></span>

      <%= link_to vote_path(idea.id), method: :delete,  remote: true ,id:"vote-down-#{idea.id}" do %>
        <i class="fa fa-lg fa-thumbs-down vote vote-down" aria-hidden="true"></i>
      <% end %>

    </section>
    <div class="clearfix"></div>

  </section>
</div>

app/views/ideas/index.html.erb
<article class="index-ideas" style="background-image:url('<%= asset_url 'bg-pattern.png' %>')">
  <section class="container">
  <section class="row headerRow">
    <section class="col-md-2">
      <object data="<%= asset_url 'logo-2.svg' %>" type="image/svg+xml" style="width:140px"></object>
    </section>

    <section class="col-md-8 text-center">
      <h4 style="margin: 40px 0 15px 0;">Estas son las respuestas de otras personas</h4>
      <h2 style="margin: 0 0 18px 0">tú eres el juez, ¿cuáles validas?</h2>
      <div class="clearfix"></div>
    </section>
  </section>


  <section class="row text-center">

    <div id="sticky-anchor"></div>
    <a href="<%= la_verdad_path %>"><div id="sticky">¿Y ahora qué?</div></a>
  </section>

  <div id="posts">
    <section class="text-right"><a  style="text-align:right !important" href="<%= mas_votadas_path %>">Random</a>
    <section class="text-right"><a  style="text-align:right !important" href="<%= idea_path %>">Mas votadas</a>
</section>
    <%= render @ideas %>
  </div>

  <%= will_paginate @ideas %>
  </section>
</article>

<script>
$(document).ready(function() {
if ($('.pagination').length) {
  $(window).scroll(function() {
    var url = $('.pagination .next_page').attr('href');
    if (url && $(window).scrollTop() > $(document).height() - $(window).height() - 50) {
      $('.pagination').text("Please Wait...");
      return $.getScript(url);
    }
  });
  return $(window).scroll();
}
});
</script>


<script>
function sticky_relocate() {
  var window_top = $(window).scrollTop();
  var div_top = $('#sticky-anchor').offset().top;
  if (window_top > div_top) {
      $('#sticky').addClass('stick');
      $('#sticky-anchor').height($('#sticky').outerHeight());
  } else {
      $('#sticky').removeClass('stick');
      $('#sticky-anchor').height(0);
  }
}

$(function() {
  $(window).scroll(sticky_relocate);
  sticky_relocate();
});

var dir = 1;
var MIN_TOP = 200;
var MAX_TOP = 350;

function autoscroll() {
  var window_top = $(window).scrollTop() + dir;
  if (window_top >= MAX_TOP) {
      window_top = MAX_TOP;
      dir = -1;
  } else if (window_top <= MIN_TOP) {
      window_top = MIN_TOP;
      dir = 1;
  }
  $(window).scrollTop(window_top);
  window.setTimeout(autoscroll, 100);
}
</script>

app/views/ideas/index.js.erb
$('#posts').append('<%= escape_javascript render(@ideas) %>');
$('.pagination').replaceWith('<%= escape_javascript will_paginate(@ideas) %>');

app/views/ideas/la_verdad.html.erb
<section class="col-md-5 visible-md-block visible-lg-block" style="background-image:url('<%= asset_url "speaker.jpg" %>'); background-size:cover; height:100%;">
</section>

<section class="col-md-7 la_verdad index-ideas" style="background-image:url('<%= asset_url 'bg-pattern.png' %>'); height:100%;">
  <br><object data="<%= asset_url 'logo-2.svg' %>" type="image/svg+xml" width="200px"></object>

    <h5>Hoy hiciste uso de la Libertad de expresión, participando y comparando tu opinión con la de otros, estando de acuerdo, o no, empatizando o discerniendo con ellos. </h5>
    <h3>Y entonces, ¿qué es la Libertad de Expresión?</h3>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Según la Declaración Universal de los Derechos Humanos, en su artículo 19:
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        "Todo individuo tiene derecho a la libertad de opinión y de expresión; este derecho incluye el de no ser molestado a causa de sus opiniones, el de investigar y recibir informaciones y opiniones, y el de difundirlas, sin limitación de fronteras, por cualquier medio de expresión."
        <a href="http://www.un.org/es/documents/udhr/">Leer más </a>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Según la Comisión Interamericana de Derechos Humanos:
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
        “..la consolidación y desarrollo de la democracia depende de la existencia de libertad de expresión… ” ya que “el derecho a la libertad de expresión es esencial para el desarrollo del conocimiento y del entendimiento entre los pueblos, que conducirá a una verdadera comprensión y cooperación entre las naciones del hemisferio… cuando se obstaculiza el libre debate de ideas y opiniones se limita la libertad de expresión y el efectivo desarrollo del proceso democrático.”
        <a href="https://www.cidh.oas.org/basicos/basicos13.htm">Leer más </a>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Según article19.org:
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
        “El derecho a la libertad de expresión no sólo se aplica a las informaciones e ideas generalmente consideradas útiles o correctas. También se aplica a cualquier tipo de hecho u opinión que puede ser comunicado. El Comité de Derechos Humanos de la ONU ha enfatizado que la ‘expresión’ es amplia y no está limitada a expresión política, cultural o artística. También incluye expresiones controversiales, falsas e incluso chocantes. El mero hecho que una idea sea desagradable o sea considerada incorrecta no justifica su censura.”
        <a href="https://www.article19.org/pages/es/key-aspects.html">Leer Más</a>
      </div>
    </div>
  </div>
</div>

    <h3>No te quedes callado. Comparte:</h3>

    <section class="social_share">
      <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http://paratiquees.mx&title=¿Para ti que es la libertad de expresión?"><i class="fa fa-facebook-square fa-3x"></i></a>
      <a target="_blank" href="https://www.twitter.com/intent/tweet?url=http://paratiquees.mx&text=¿Para ti que es la libertad de expresión?"><i class="fa fa-twitter-square fa-3x"></i></a>
    </section>

    <h6>La Libertad de Expresión puede cambiar una sociedad,úsala con responsabilidad. </h6>

</section>

app/views/ideas/new.html.erb
<article class="main-question text-center bg" style="background-image:url('<%= asset_url "bg.jpg" %>')">

  <section style="margin-bottom:65px">
    <object type="image/svg+xml" data="<%= asset_url "logo-1.svg" %>" style="width:300px;margin-top:70px;">Your browser does not support SVG</object>

    <h2>Escribe tu definición y ve qué sucede</h2>

      <section class="col-md-6 col-md-push-3">
        <%= form_for @idea do |f| %>
          <%= f.text_area :content,  class:"form-control space20px" ,rows: "4" %>
          <%= f.hidden_field :theme_id , value: @theme.id.to_s %>
          <%= f.submit "Enviar Respuesta", class: "btn new-btn btn-amarillo "%>
        <% end %>
      </section>
      <div class="clearfix"></div>
    </section>

    <%= render 'shared/footer' %>

</article>

app/views/ideas/show.html.erb
<article class="index-ideas" style="height: 100%;background-image:url('<%= asset_url 'bg-pattern.png' %>')">
  <section class="container">
  <section class="row headerRow">
    <section class="col-md-2">
    </section>

    <section class="col-md-8 text-center"><br>
      <object data="<%= asset_url 'logo-2.svg' %>" type="image/svg+xml" style="width:250px"></object>
      <h2>Esto es lo que alguién más opina, ¿Estás de acuerdo?</h2><br>
      <dic class="clearfix"></dic>
    </section>
  </section>

  <div id="posts">
    <div class="post">
      <section class="col-md-6 col-md-push-3 post-content">
        <p><%= @idea.content %></p>


        <section class="share-container pull-left">
          <%= social_share request.original_url+'/ideas/ver/'+@idea.id.to_s,'Para mí, esto es la Libertad de Expresión #ParaTiQueEs'  %>
        </section>

        <section class="like-container pull-right">
          <span class="counter" id="counter-plus-<%= @idea.id %>"><%= @idea.votePlus %></span>

          <%= link_to vote_path(@idea.id), method: :post,  remote: true, id:"vote-up-#{@idea.id}"  do %>
            <i class="fa fa-lg fa-thumbs-up vote vote-up" aria-hidden="true"></i>
          <% end %>

          <span class="counter" id="counter-less-<%= @idea.id %>"><%= @idea.voteLess %></span>

          <%= link_to vote_path(@idea.id), method: :delete,  remote: true ,id:"vote-down-#{@idea.id}" do %>
            <i class="fa fa-lg fa-thumbs-down vote vote-down" aria-hidden="true"></i>
          <% end %>

        </section>

      </section>
    </div>

  </div>

  <div class="clearfix"></div>
  <section class="col-md-12 text-center"><br>
    <a href="<%= new_idea_path(@idea.theme.slug) %>" class="btn btn-verde">¿Y PARA TI QUÉ ES? OPINA</a>
  </section>
  </section>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Opinion</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta property="og:type"               content="article" />
  <meta property="og:image"              content="http://s32.postimg.org/p2gguklk5/ptqes.jpg" />

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Titillium+Web:400,700' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<section class="container">
  <section class="row">
<footer class="col-md-6 col-md-push-3" style="margin:3px 15px">
      <section class="pull-left">
        <p class="social_share">Compartir: <%= social_share 'http://paratiquees.mx','Día Mundial de la Libertad de Expresión, ¿sabes exactamente de qué se trata?' %></p>
      </section>

      <section class="pull-right">
        <object style="width:32px" data="<%= asset_url 'logo-pachuco-blanco.svg' %>" type="image/svg+xml"></object>
      </section>
</footer>
</section>

</section>

app/views/statics/home.html.erb
<div class="jumbotron home text-center" style="background-image:url('<%= asset_url "bg-home.jpg" %>')">
    <div class="container">
        <h1>Encuestas relevantes para gente relevante</h1>
        <h3>Ultimas encuestas </h3>
        <% @temas.each do |tema| %>
          <%= link_to tema.title, "ideas/#{tema.slug}/proponer" %>
        <% end %>
    </div>
</div>

app/views/votes/create.js.erb
$('#counter-plus-'+<%= @idea.id %>).text('<%= @idea.votePlus %>');
$('#vote-up-'+<%= @idea.id %>).removeAttr('href');
$('#vote-up-'+<%= @idea.id %>+'> i').addClass('voted');

app/views/votes/destroy.js.erb
$('#counter-less-'+<%= @idea.id %>).text('<%= @idea.voteLess %>');
$('#vote-down-'+<%= @idea.id %>).removeAttr('href');
$('#vote-down-'+<%= @idea.id %>+'> i').addClass('voted');